<?php
/**
 * ForeTELL Lite — report.php
 * Generates a downloadable Word (.docx) security report using a pure PHP
 * approach (HTML sent as application/msword) since the EM environment has
 * no Composer / PhpWord available. Opens directly in Word / LibreOffice.
 */

$module = $GLOBALS['module'];

// ── Helpers ──────────────────────────────────────────────────────────────────

function ftl_h($str): string {
    return htmlspecialchars((string)$str, ENT_QUOTES, 'UTF-8');
}

function ftl_badge_word(string $sev): string {
    $colours = [
        'CRITICAL' => '#7b0000', 'HIGH' => '#c0392b',
        'MEDIUM'   => '#e67e22', 'Info' => '#2980b9',
    ];
    $bg = $colours[$sev] ?? '#555';
    return "<span style='background:{$bg};color:#fff;padding:1pt 5pt;font-size:9pt;'>" . ftl_h($sev) . "</span>";
}

// ── Collect all data ──────────────────────────────────────────────────────────

$today          = date('Y-m-d H:i:s');
$days           = $module->getWindowDays();
$windowLabel    = $days === 1 ? 'last 24 hours' : "last {$days} days";
[$ohStart, $ohEnd] = $module->getOffHoursBounds();

$todayPriorities  = $module->getTodayHighPriorities();
$suspiciousLogins = $module->getSuspiciousLogins();
$ipAnomalies      = $module->getIPAnomalies();
$userAnomalies    = $module->getUserActivityAnomalies();
$systemEvents     = $module->getSystemEvents();
$offHoursEvents   = $module->getOffHoursEvents();

// High-severity system events only for the summary paragraph
$highEvents = array_values(array_filter($systemEvents, function($r) {
    return in_array($r['event'], ['USER_RIGHTS', 'API_TOKEN_CREATE', 'USER_CREATE'], true);
}));

// ── Output headers ────────────────────────────────────────────────────────────

$filename = 'ForeTELL_Lite_Security_Report_' . date('Y-m-d') . '.doc';
header('Content-Type: application/msword');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-cache, no-store, must-revalidate');

?><!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="UTF-8">
<!--[if gte mso 9]>
<xml><w:WordDocument><w:View>Print</w:View><w:Zoom>90</w:Zoom></w:WordDocument></xml>
<![endif]-->
<style>
  body        { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #222; margin: 2cm; }
  h1          { font-size: 20pt; color: #1F4E79; border-bottom: 2pt solid #1F4E79; padding-bottom: 4pt; }
  h2          { font-size: 14pt; color: #2E74B5; margin-top: 18pt; margin-bottom: 6pt; }
  h3          { font-size: 11pt; color: #333; margin-top: 12pt; margin-bottom: 4pt; }
  p           { margin: 4pt 0 8pt 0; line-height: 1.4; }
  table       { border-collapse: collapse; width: 100%; margin-bottom: 12pt; font-size: 9pt; }
  th          { background: #1F4E79; color: #fff; padding: 5pt 8pt; text-align: left; font-weight: bold; }
  td          { border: 0.5pt solid #ccc; padding: 4pt 8pt; vertical-align: top; }
  tr.alt      { background: #f2f2f2; }
  .crit-row   { background: #fcd2d2; }
  .high-row   { background: #ffe7cc; }
  .summary-box { border: 1pt solid #2E74B5; background: #EBF3FB; padding: 8pt 12pt; margin-bottom: 14pt; }
  .clean      { color: #27ae60; font-weight: bold; }
  .footer     { font-size: 8pt; color: #999; border-top: 0.5pt solid #ccc; margin-top: 24pt; padding-top: 6pt; }
  code        { font-family: Consolas, monospace; font-size: 9pt; background: #f4f4f4; padding: 0 3pt; }
  .page-break { page-break-before: always; }
</style>
</head>
<body>

<!-- ══ COVER ══════════════════════════════════════════════════════════════ -->
<h1>
    ForeTELL Lite — Security Intelligence Report
</h1>

<div class="summary-box">
<table style="border:none; width:100%;">
<tr><td style="border:none; width:35%; font-weight:bold; color:#1F4E79;">Report Generated</td><td style="border:none;"><?= ftl_h($today) ?></td></tr>
<tr><td style="border:none; font-weight:bold; color:#1F4E79;">Analysis Window</td><td style="border:none;"><?= ftl_h($windowLabel) ?></td></tr>
<tr><td style="border:none; font-weight:bold; color:#1F4E79;">Off-Hours Window</td><td style="border:none;"><?= ftl_h($ohStart) ?> &ndash; <?= ftl_h($ohEnd) ?></td></tr>
<tr><td style="border:none; font-weight:bold; color:#1F4E79;">REDCap Instance</td><td style="border:none;">wcredcap.wchospital.ca</td></tr>
<tr><td style="border:none; font-weight:bold; color:#1F4E79;">Prepared By</td><td style="border:none;">ForeTELL Lite v1.0.2 &mdash; WCH REDCap System Administration</td></tr>
</table>
</div>

<!-- ══ EXECUTIVE SUMMARY ══════════════════════════════════════════════════ -->
<h2>1. Executive Summary</h2>
<p>
This report summarises security intelligence generated by ForeTELL Lite for the analysis window
(<strong><?= ftl_h($windowLabel) ?></strong>).
</p>

<table>
<tr>
    <th>Category</th>
    <th>Count</th>
    <th>Status</th>
</tr>
<?php
$summary = [
    ["Today's Priorities (since midnight)",   count($todayPriorities),  count($todayPriorities) > 0  ? '<span style="color:#c0392b;font-weight:bold;">⚠ Action Required</span>' : '<span class="clean">✓ Clean</span>'],
    ['Suspicious Login Patterns',              count($suspiciousLogins), count($suspiciousLogins) > 0 ? '<span style="color:#e67e22;font-weight:bold;">⚠ Review</span>'           : '<span class="clean">✓ Clean</span>'],
    ['IP Anomalies',                           count($ipAnomalies),      count($ipAnomalies) > 0      ? '<span style="color:#e67e22;font-weight:bold;">⚠ Review</span>'           : '<span class="clean">✓ Clean</span>'],
    ['User Activity Anomalies',                count($userAnomalies),    count($userAnomalies) > 0    ? '<span style="color:#e67e22;font-weight:bold;">⚠ Review</span>'           : '<span class="clean">✓ Clean</span>'],
    ['High-Severity System Events',            count($highEvents),       count($highEvents) > 0       ? '<span style="color:#c0392b;font-weight:bold;">⚠ Action Required</span>' : '<span class="clean">✓ Clean</span>'],
    ['Off-Hours Events',                       count($offHoursEvents),   count($offHoursEvents) > 0   ? '<span style="color:#8e44ad;font-weight:bold;">ℹ Review</span>'           : '<span class="clean">✓ Clean</span>'],
];
foreach ($summary as $i => $row): ?>
<tr <?= $i % 2 === 1 ? 'class="alt"' : '' ?>>
    <td><?= $row[0] ?></td>
    <td style="text-align:center; font-weight:bold;"><?= number_format((int)$row[1]) ?></td>
    <td><?= $row[2] ?></td>
</tr>
<?php endforeach; ?>
</table>

<!-- ══ SECTION 2: TODAY'S PRIORITIES ══════════════════════════════════════ -->
<div class="page-break"></div>
<h2>2. Today's High-Priority Incidents</h2>
<p>
Incidents flagged since midnight today. Covers honey-pot probing, brute-force authentication
bursts, high-severity privilege events, and high-volume data exports.
</p>

<?php if (empty($todayPriorities)): ?>
<p class="clean">✓ No high-priority incidents recorded today.</p>
<?php else: ?>
<table>
<tr><th>Timestamp</th><th>Severity</th><th>Incident Type</th><th>User</th><th>Source IP</th><th>Diagnostics</th></tr>
<?php foreach ($todayPriorities as $a):
    $rowClass = $a['severity'] === 'CRITICAL' ? 'crit-row' : ($a['severity'] === 'HIGH' ? 'high-row' : '');
?>
<tr class="<?= $rowClass ?>">
    <td style="white-space:nowrap; font-size:9pt;"><?= ftl_h($a['ts']) ?></td>
    <td><?= ftl_badge_word($a['severity']) ?></td>
    <td style="font-weight:600;"><?= ftl_h($a['incident']) ?></td>
    <td><code><?= ftl_h($a['user']) ?></code></td>
    <td><code><?= ftl_h($a['ip']) ?></code></td>
    <td style="font-size:9pt;"><?= ftl_h($a['diagnostics']) ?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<!-- ══ SECTION 3: SUSPICIOUS LOGINS ════════════════════════════════════════ -->
<div class="page-break"></div>
<h2>3. Suspicious Login Patterns</h2>
<p>
User + IP + day combinations with repeated authentication failures exceeding the configured threshold.
</p>

<?php if (empty($suspiciousLogins)): ?>
<p class="clean">✓ No suspicious login patterns detected in this window.</p>
<?php else: ?>
<table>
<tr><th>User</th><th>IP Address</th><th>Date</th><th>Failures</th><th>Signal</th></tr>
<?php foreach ($suspiciousLogins as $i => $row):
    $thr = $module->getThreshold('threshold_suspicious_logins', 6);
    if ($row['cnt'] >= $thr * 3)     $sev = 'HIGH';
    elseif ($row['cnt'] >= $thr * 2) $sev = 'MEDIUM';
    else                              $sev = 'Info';
?>
<tr <?= $i % 2 === 1 ? 'class="alt"' : '' ?>>
    <td><code><?= ftl_h($row['user']) ?></code></td>
    <td><code><?= ftl_h($row['ip']) ?></code></td>
    <td><?= ftl_h($row['ts_date']) ?></td>
    <td style="text-align:center; font-weight:bold;"><?= (int)$row['cnt'] ?></td>
    <td><?= ftl_badge_word($sev) ?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<!-- ══ SECTION 4: IP ANOMALIES ══════════════════════════════════════════════ -->
<h2>4. IP Anomalies</h2>
<p>
IP addresses generating abnormal authentication failure volumes or accessing the system under multiple distinct user accounts.
</p>

<?php if (empty($ipAnomalies)): ?>
<p class="clean">✓ No IP anomalies detected in this window.</p>
<?php else: ?>
<table>
<tr><th>IP Address</th><th>Total Failures</th><th>Distinct Users</th><th>Signal</th><th>First Seen</th><th>Last Seen</th></tr>
<?php
$thr_ev = $module->getThreshold('threshold_ip_events', 10);
$thr_us = $module->getThreshold('threshold_ip_users', 3);
foreach ($ipAnomalies as $i => $row):
    $sev = $row['distinct_users'] >= $thr_us ? 'HIGH' : 'MEDIUM';
?>
<tr <?= $i % 2 === 1 ? 'class="alt"' : '' ?>>
    <td><code><?= ftl_h($row['ip']) ?></code></td>
    <td style="text-align:center;"><?= number_format((int)$row['total_events']) ?></td>
    <td style="text-align:center;"><?= (int)$row['distinct_users'] ?></td>
    <td><?= ftl_badge_word($sev) ?></td>
    <td style="font-size:9pt;"><?= ftl_h($row['first_seen']) ?></td>
    <td style="font-size:9pt;"><?= ftl_h($row['last_seen']) ?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<!-- ══ SECTION 5: USER ACTIVITY ══════════════════════════════════════════════ -->
<div class="page-break"></div>
<h2>5. User Activity Anomalies</h2>
<p>
Users exceeding the configured event count or distinct source IP thresholds over the analysis window.
</p>

<?php if (empty($userAnomalies)): ?>
<p class="clean">✓ No user activity anomalies detected in this window.</p>
<?php else: ?>
<table>
<tr><th>User</th><th>Total Events</th><th>Distinct IPs</th><th>First Seen</th><th>Last Seen</th></tr>
<?php foreach ($userAnomalies as $i => $row): ?>
<tr <?= $i % 2 === 1 ? 'class="alt"' : '' ?>>
    <td><code><?= ftl_h($row['user']) ?></code></td>
    <td style="text-align:center;"><?= number_format((int)$row['total_events']) ?></td>
    <td style="text-align:center;"><?= (int)$row['distinct_ips'] ?></td>
    <td style="font-size:9pt;"><?= ftl_h($row['first_seen']) ?></td>
    <td style="font-size:9pt;"><?= ftl_h($row['last_seen']) ?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<!-- ══ SECTION 6: SYSTEM EVENTS ══════════════════════════════════════════════ -->
<h2>6. System Events</h2>
<p>
High-severity system events (USER_RIGHTS, API_TOKEN_CREATE, USER_CREATE) and medium-severity
data operations (DATA_EXPORT, DOC_UPLOAD, DOC_DELETE) recorded in the analysis window.
</p>

<?php if (empty($systemEvents)): ?>
<p class="clean">✓ No system events recorded in this window.</p>
<?php else:
    $highEvList   = ['USER_RIGHTS', 'API_TOKEN_CREATE', 'USER_CREATE'];
    $medEvList    = ['DATA_EXPORT', 'DOC_UPLOAD', 'DOC_DELETE'];
?>
<table>
<tr><th>Timestamp</th><th>User</th><th>IP</th><th>Event</th><th>Signal</th><th>Project</th><th>Page</th></tr>
<?php foreach ($systemEvents as $i => $row):
    if (in_array($row['event'], $highEvList, true))     $sev = 'HIGH';
    elseif (in_array($row['event'], $medEvList, true))  $sev = 'MEDIUM';
    else                                                 $sev = 'Info';
    $rowClass = ($i % 2 === 1) ? 'alt' : '';
    if ($sev === 'HIGH') $rowClass = 'high-row';
?>
<tr class="<?= $rowClass ?>">
    <td style="white-space:nowrap; font-size:9pt;"><?= ftl_h($row['ts']) ?></td>
    <td><code><?= ftl_h($row['user']) ?></code></td>
    <td><code><?= ftl_h($row['ip']) ?></code></td>
    <td><code><?= ftl_h($row['event']) ?></code></td>
    <td><?= ftl_badge_word($sev) ?></td>
    <td><?= ftl_h($row['project_id'] ?? '') ?></td>
    <td style="font-size:9pt; color:#666;"><?= ftl_h(basename((string)($row['page'] ?? ''))) ?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<!-- ══ SECTION 7: OFF-HOURS ══════════════════════════════════════════════════ -->
<div class="page-break"></div>
<h2>7. Off-Hours Activity</h2>
<p>
Events occurring outside core hours (<?= ftl_h($ohStart) ?> &ndash; <?= ftl_h($ohEnd) ?>)
in the analysis window.
<?= count($offHoursEvents) > 0
    ? '<strong>' . number_format(count($offHoursEvents)) . ' off-hours events</strong> recorded.'
    : '' ?>
</p>

<?php if (empty($offHoursEvents)): ?>
<p class="clean">✓ No off-hours activity detected.</p>
<?php else:
    // Aggregate by user for the Word report (cleaner than raw event list)
    $ohByUser = [];
    foreach ($offHoursEvents as $r) {
        $u = (string)$r['user'];
        if (!isset($ohByUser[$u])) $ohByUser[$u] = ['cnt' => 0, 'last' => ''];
        $ohByUser[$u]['cnt']++;
        if ($r['ts'] > $ohByUser[$u]['last']) $ohByUser[$u]['last'] = $r['ts'];
    }
    arsort($ohByUser);
?>
<table>
<tr><th>User</th><th>Off-Hours Events</th><th>Last Activity</th></tr>
<?php foreach ($ohByUser as $u => $info): ?>
<tr>
    <td><code><?= ftl_h($u) ?></code></td>
    <td style="text-align:center; font-weight:bold;"><?= number_format($info['cnt']) ?></td>
    <td style="font-size:9pt;"><?= ftl_h($info['last']) ?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<!-- ══ FOOTER ══════════════════════════════════════════════════════════════ -->
<div class="footer">
    <p>
        <strong>ForeTELL Lite v1.0.2</strong> &mdash; WCH REDCap Security Monitoring &mdash; Women's College Hospital<br>
        Generated: <?= ftl_h(date('Y-m-d H:i:s')) ?> &mdash; Analysis window: <?= ftl_h($windowLabel) ?><br>
        <em>CONFIDENTIAL &mdash; For internal security team use only. Retain per WCH document retention policy.</em>
    </p>
</div>

</body>
</html>
